version: '3.8'

services:
  db:
    image: postgis/postgis:latest
    container_name: postgis_container
    environment:
      POSTGRES_USER: mgUser
      POSTGRES_PASSWORD: mgPassword
      POSTGRES_DB: mg-case-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]  # Verilerin kalıcı olması için AOF modunu açıyoruz
    volumes:
      - redisdata:/data

  app:
    build:
      context: .
    container_name: mg-courier-tracking
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mg-case-db
      SPRING_DATASOURCE_USERNAME: mgUser
      SPRING_DATASOURCE_PASSWORD: mgPassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: always
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
