-- STORE INSERTS
INSERT INTO STORE (ID, NAME, LOCATION, VERSION, CREATOR_USER, CREATION_DATE, UPDATER_USER, UPDATE_DATE) VALUES
(1, 'Ataşehir MMM Migros', ST_GeomFromText('POINT(29.1244229 40.9923307)', 4326), 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Novada MMM Migros', ST_GeomFromText('POINT(29.1161293 40.986106)', 4326), 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Beylikdüzü 5M Migros', ST_GeomFromText('POINT(28.6552262 41.0066851)', 4326), 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Ortaköy MMM Migros', ST_GeomFromText('POINT(29.0210292 41.055783)', 4326), 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Caddebostan MMM Migros', ST_GeomFromText('POINT(29.0630908 40.9632463)', 4326), 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
ALTER SEQUENCE STORE_SEQ RESTART WITH 6;

-- COURIER INSERTS
INSERT INTO COURIER (ID, FIRST_NAME, LAST_NAME, TOTAL_DISTANCE, VERSION, CREATOR_USER, CREATION_DATE, UPDATER_USER, UPDATE_DATE) VALUES
(1, 'Ahmet', 'Yılmaz', 0, 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(2, 'Merve', 'Şahin', 0, 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(3, 'Fatma', 'Baş', 0, 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(4, 'Mehmet', 'Kaya', 0, 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
(5, 'Selim', 'Koç', 0, 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);
ALTER SEQUENCE COURIER_SEQ RESTART WITH 6;