-- STORE TABLE CREATION
DROP TABLE IF EXISTS STORE CASCADE;
DROP SEQUENCE IF EXISTS STORE_SEQ;
CREATE SEQUENCE STORE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE STORE (
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    LOCATION GEOMETRY,
    VERSION BIGINT DEFAULT 1,
    CREATOR_USER VARCHAR(100),
    CREATION_DATE TIMESTAMP,
    UPDATER_USER VARCHAR(100),
    UPDATE_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);