-- STORE TABLE CREATION
DROP TABLE IF EXISTS STORE CASCADE;
DROP SEQUENCE IF EXISTS STORE_SEQ;
CREATE SEQUENCE STORE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE STORE (
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    LOCATION GEOGRAPHY(POINT, 4326) NOT NULL,

    VERSION BIGINT DEFAULT 1 NOT NULL,
    CREATOR_USER VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATER_USER VARCHAR(100),
    UPDATE_DATE TIMESTAMP,

    PRIMARY KEY (ID)
);

-- COURIER TABLE CREATION
DROP TABLE IF EXISTS COURIER CASCADE;
DROP SEQUENCE IF EXISTS COURIER_SEQ;
CREATE SEQUENCE COURIER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE COURIER (
    ID BIGINT NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    TOTAL_DISTANCE DECIMAL(10, 2) DEFAULT 0 NOT NULL,

    VERSION BIGINT DEFAULT 1 NOT NULL,
    CREATOR_USER VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATER_USER VARCHAR(100),
    UPDATE_DATE TIMESTAMP,

    PRIMARY KEY (ID)
);

-- COURIER_GEO_SIGNAL TABLE CREATION
DROP TABLE IF EXISTS COURIER_GEO_SIGNAL CASCADE;
DROP SEQUENCE IF EXISTS COURIER_GEO_SIGNAL_SEQ;
CREATE SEQUENCE COURIER_GEO_SIGNAL_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE COURIER_GEO_SIGNAL (
    ID BIGINT NOT NULL,
    COURIER_ID BIGINT NOT NULL,
    LOCATION GEOGRAPHY(POINT, 4326) NOT NULL,
    COURIER_TIME TIMESTAMP NOT NULL,

    VERSION BIGINT DEFAULT 1 NOT NULL,
    CREATOR_USER VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,

    PRIMARY KEY (ID)
);

-- COURIER_DRIVE TABLE CREATION
DROP TABLE IF EXISTS COURIER_DRIVE CASCADE;
DROP SEQUENCE IF EXISTS COURIER_DRIVE_SEQ;
CREATE SEQUENCE COURIER_DRIVE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE COURIER_DRIVE (
    ID BIGINT NOT NULL,
    COURIER_ID BIGINT NOT NULL,
    STARTER_GEO_SIGNAL_ID BIGINT NOT NULL,
    FINISHER_GEO_SIGNAL_ID BIGINT,

    VERSION BIGINT DEFAULT 1 NOT NULL,
    CREATOR_USER VARCHAR(100) NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    UPDATER_USER VARCHAR(100),
    UPDATE_DATE TIMESTAMP,

    PRIMARY KEY (ID)
);